import {
  BarChart3,
  Blocks,
  Bot,
  Cloud,
  Code2,
  Contact,
  Database,
  Globe,
  Megaphone,
  MessageCircle,
  ShoppingBag,
  Sparkles,
  Table2,
  Target,
  Triangle,
  Users,
  Video,
  Workflow,
} from 'lucide-react'
import type { TechItem } from '@/lib/types'

export const TECH_STACK: TechItem[] = [
  { id: 'meta-ads', name: 'Meta Ads', icon: Megaphone },
  { id: 'google-ads', name: 'Google Ads', icon: Target },
  { id: 'gohighlevel', name: 'GoHighLevel (GHL)', icon: Users },
  { id: 'zoho-crm', name: 'Zoho CRM', icon: Contact },
  { id: 'make', name: 'Make', icon: Blocks },
  { id: 'n8n', name: 'n8n', icon: Workflow },
  { id: 'lovable', name: 'Lovable', icon: Sparkles },
  { id: 'supabase', name: 'Supabase', icon: Database },
  { id: 'google-sheets', name: 'Google Sheets', icon: Table2 },
  { id: 'tiktok-ads', name: 'TikTok Ads', icon: Video },
  { id: 'nextjs', name: 'Next.js', icon: Code2 },
  { id: 'vercel', name: 'Vercel', icon: Triangle },
  { id: 'shopify', name: 'Shopify', icon: ShoppingBag },
  { id: 'manychat', name: 'ManyChat', icon: MessageCircle },
  { id: 'gcp', name: 'GCP', icon: Cloud },
  { id: 'wordpress', name: 'WordPress', icon: Globe },
  { id: 'fathom', name: 'Fathom', icon: BarChart3 },
  { id: 'claude', name: 'Claude', icon: Bot },
]
